// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SystemStatsMonitorService.proto

package v1grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartMonitoringRequest struct {
	ResponseDuration     int64    `protobuf:"varint,1,opt,name=response_duration,json=responseDuration,proto3" json:"response_duration,omitempty"`
	WaitDuration         int64    `protobuf:"varint,2,opt,name=wait_duration,json=waitDuration,proto3" json:"wait_duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartMonitoringRequest) Reset()         { *m = StartMonitoringRequest{} }
func (m *StartMonitoringRequest) String() string { return proto.CompactTextString(m) }
func (*StartMonitoringRequest) ProtoMessage()    {}
func (*StartMonitoringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1122009af0fe3cde, []int{0}
}

func (m *StartMonitoringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartMonitoringRequest.Unmarshal(m, b)
}
func (m *StartMonitoringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartMonitoringRequest.Marshal(b, m, deterministic)
}
func (m *StartMonitoringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartMonitoringRequest.Merge(m, src)
}
func (m *StartMonitoringRequest) XXX_Size() int {
	return xxx_messageInfo_StartMonitoringRequest.Size(m)
}
func (m *StartMonitoringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartMonitoringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartMonitoringRequest proto.InternalMessageInfo

func (m *StartMonitoringRequest) GetResponseDuration() int64 {
	if m != nil {
		return m.ResponseDuration
	}
	return 0
}

func (m *StartMonitoringRequest) GetWaitDuration() int64 {
	if m != nil {
		return m.WaitDuration
	}
	return 0
}

type StatsResponse struct {
	CpuInfo               *CPUTimeStatValue       `protobuf:"bytes,1,opt,name=cpu_info,json=cpuInfo,proto3" json:"cpu_info,omitempty"`
	LoadInfo              *LoadStatValue          `protobuf:"bytes,2,opt,name=load_info,json=loadInfo,proto3" json:"load_info,omitempty"`
	NetworkStateInfo      *NetworkStateStatValue  `protobuf:"bytes,3,opt,name=network_state_info,json=networkStateInfo,proto3" json:"network_state_info,omitempty"`
	NetworkStatisticsInfo *NetworkStatisticsValue `protobuf:"bytes,4,opt,name=network_statistics_info,json=networkStatisticsInfo,proto3" json:"network_statistics_info,omitempty"`
	DiskUsageInfo         *DiskUsageValue         `protobuf:"bytes,5,opt,name=disk_usage_info,json=diskUsageInfo,proto3" json:"disk_usage_info,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1122009af0fe3cde, []int{1}
}

func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetCpuInfo() *CPUTimeStatValue {
	if m != nil {
		return m.CpuInfo
	}
	return nil
}

func (m *StatsResponse) GetLoadInfo() *LoadStatValue {
	if m != nil {
		return m.LoadInfo
	}
	return nil
}

func (m *StatsResponse) GetNetworkStateInfo() *NetworkStateStatValue {
	if m != nil {
		return m.NetworkStateInfo
	}
	return nil
}

func (m *StatsResponse) GetNetworkStatisticsInfo() *NetworkStatisticsValue {
	if m != nil {
		return m.NetworkStatisticsInfo
	}
	return nil
}

func (m *StatsResponse) GetDiskUsageInfo() *DiskUsageValue {
	if m != nil {
		return m.DiskUsageInfo
	}
	return nil
}

type CPUTimeStatValue struct {
	User                 float64  `protobuf:"fixed64,1,opt,name=user,proto3" json:"user,omitempty"`
	System               float64  `protobuf:"fixed64,2,opt,name=system,proto3" json:"system,omitempty"`
	Idle                 float64  `protobuf:"fixed64,3,opt,name=idle,proto3" json:"idle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPUTimeStatValue) Reset()         { *m = CPUTimeStatValue{} }
func (m *CPUTimeStatValue) String() string { return proto.CompactTextString(m) }
func (*CPUTimeStatValue) ProtoMessage()    {}
func (*CPUTimeStatValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1122009af0fe3cde, []int{2}
}

func (m *CPUTimeStatValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPUTimeStatValue.Unmarshal(m, b)
}
func (m *CPUTimeStatValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPUTimeStatValue.Marshal(b, m, deterministic)
}
func (m *CPUTimeStatValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPUTimeStatValue.Merge(m, src)
}
func (m *CPUTimeStatValue) XXX_Size() int {
	return xxx_messageInfo_CPUTimeStatValue.Size(m)
}
func (m *CPUTimeStatValue) XXX_DiscardUnknown() {
	xxx_messageInfo_CPUTimeStatValue.DiscardUnknown(m)
}

var xxx_messageInfo_CPUTimeStatValue proto.InternalMessageInfo

func (m *CPUTimeStatValue) GetUser() float64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *CPUTimeStatValue) GetSystem() float64 {
	if m != nil {
		return m.System
	}
	return 0
}

func (m *CPUTimeStatValue) GetIdle() float64 {
	if m != nil {
		return m.Idle
	}
	return 0
}

type LoadStatValue struct {
	Load1                float64  `protobuf:"fixed64,1,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5                float64  `protobuf:"fixed64,2,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15               float64  `protobuf:"fixed64,3,opt,name=load15,proto3" json:"load15,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadStatValue) Reset()         { *m = LoadStatValue{} }
func (m *LoadStatValue) String() string { return proto.CompactTextString(m) }
func (*LoadStatValue) ProtoMessage()    {}
func (*LoadStatValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1122009af0fe3cde, []int{3}
}

func (m *LoadStatValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadStatValue.Unmarshal(m, b)
}
func (m *LoadStatValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadStatValue.Marshal(b, m, deterministic)
}
func (m *LoadStatValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadStatValue.Merge(m, src)
}
func (m *LoadStatValue) XXX_Size() int {
	return xxx_messageInfo_LoadStatValue.Size(m)
}
func (m *LoadStatValue) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadStatValue.DiscardUnknown(m)
}

var xxx_messageInfo_LoadStatValue proto.InternalMessageInfo

func (m *LoadStatValue) GetLoad1() float64 {
	if m != nil {
		return m.Load1
	}
	return 0
}

func (m *LoadStatValue) GetLoad5() float64 {
	if m != nil {
		return m.Load5
	}
	return 0
}

func (m *LoadStatValue) GetLoad15() float64 {
	if m != nil {
		return m.Load15
	}
	return 0
}

type NetworkStateStatValue struct {
	Counters             map[string]int32 `protobuf:"bytes,1,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NetworkStateStatValue) Reset()         { *m = NetworkStateStatValue{} }
func (m *NetworkStateStatValue) String() string { return proto.CompactTextString(m) }
func (*NetworkStateStatValue) ProtoMessage()    {}
func (*NetworkStateStatValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1122009af0fe3cde, []int{4}
}

func (m *NetworkStateStatValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkStateStatValue.Unmarshal(m, b)
}
func (m *NetworkStateStatValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkStateStatValue.Marshal(b, m, deterministic)
}
func (m *NetworkStateStatValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkStateStatValue.Merge(m, src)
}
func (m *NetworkStateStatValue) XXX_Size() int {
	return xxx_messageInfo_NetworkStateStatValue.Size(m)
}
func (m *NetworkStateStatValue) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkStateStatValue.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkStateStatValue proto.InternalMessageInfo

func (m *NetworkStateStatValue) GetCounters() map[string]int32 {
	if m != nil {
		return m.Counters
	}
	return nil
}

type NetworkStatItem struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	User                 int32    `protobuf:"varint,3,opt,name=user,proto3" json:"user,omitempty"`
	Protocol             string   `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port                 int32    `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkStatItem) Reset()         { *m = NetworkStatItem{} }
func (m *NetworkStatItem) String() string { return proto.CompactTextString(m) }
func (*NetworkStatItem) ProtoMessage()    {}
func (*NetworkStatItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_1122009af0fe3cde, []int{5}
}

func (m *NetworkStatItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkStatItem.Unmarshal(m, b)
}
func (m *NetworkStatItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkStatItem.Marshal(b, m, deterministic)
}
func (m *NetworkStatItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkStatItem.Merge(m, src)
}
func (m *NetworkStatItem) XXX_Size() int {
	return xxx_messageInfo_NetworkStatItem.Size(m)
}
func (m *NetworkStatItem) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkStatItem.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkStatItem proto.InternalMessageInfo

func (m *NetworkStatItem) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *NetworkStatItem) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *NetworkStatItem) GetUser() int32 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *NetworkStatItem) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *NetworkStatItem) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type NetworkStatisticsValue struct {
	Items                []*NetworkStatItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NetworkStatisticsValue) Reset()         { *m = NetworkStatisticsValue{} }
func (m *NetworkStatisticsValue) String() string { return proto.CompactTextString(m) }
func (*NetworkStatisticsValue) ProtoMessage()    {}
func (*NetworkStatisticsValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1122009af0fe3cde, []int{6}
}

func (m *NetworkStatisticsValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkStatisticsValue.Unmarshal(m, b)
}
func (m *NetworkStatisticsValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkStatisticsValue.Marshal(b, m, deterministic)
}
func (m *NetworkStatisticsValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkStatisticsValue.Merge(m, src)
}
func (m *NetworkStatisticsValue) XXX_Size() int {
	return xxx_messageInfo_NetworkStatisticsValue.Size(m)
}
func (m *NetworkStatisticsValue) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkStatisticsValue.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkStatisticsValue proto.InternalMessageInfo

func (m *NetworkStatisticsValue) GetItems() []*NetworkStatItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type DiskUsageItem struct {
	Path                   string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Fstype                 string   `protobuf:"bytes,2,opt,name=fstype,proto3" json:"fstype,omitempty"`
	Used                   int64    `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	AvailablePercent       float64  `protobuf:"fixed64,4,opt,name=available_percent,json=availablePercent,proto3" json:"available_percent,omitempty"`
	InodeUsed              int64    `protobuf:"varint,5,opt,name=inode_used,json=inodeUsed,proto3" json:"inode_used,omitempty"`
	InodesAvailablePercent float64  `protobuf:"fixed64,6,opt,name=inodes_available_percent,json=inodesAvailablePercent,proto3" json:"inodes_available_percent,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *DiskUsageItem) Reset()         { *m = DiskUsageItem{} }
func (m *DiskUsageItem) String() string { return proto.CompactTextString(m) }
func (*DiskUsageItem) ProtoMessage()    {}
func (*DiskUsageItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_1122009af0fe3cde, []int{7}
}

func (m *DiskUsageItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskUsageItem.Unmarshal(m, b)
}
func (m *DiskUsageItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskUsageItem.Marshal(b, m, deterministic)
}
func (m *DiskUsageItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskUsageItem.Merge(m, src)
}
func (m *DiskUsageItem) XXX_Size() int {
	return xxx_messageInfo_DiskUsageItem.Size(m)
}
func (m *DiskUsageItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskUsageItem.DiscardUnknown(m)
}

var xxx_messageInfo_DiskUsageItem proto.InternalMessageInfo

func (m *DiskUsageItem) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DiskUsageItem) GetFstype() string {
	if m != nil {
		return m.Fstype
	}
	return ""
}

func (m *DiskUsageItem) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *DiskUsageItem) GetAvailablePercent() float64 {
	if m != nil {
		return m.AvailablePercent
	}
	return 0
}

func (m *DiskUsageItem) GetInodeUsed() int64 {
	if m != nil {
		return m.InodeUsed
	}
	return 0
}

func (m *DiskUsageItem) GetInodesAvailablePercent() float64 {
	if m != nil {
		return m.InodesAvailablePercent
	}
	return 0
}

type DiskUsageValue struct {
	Items                []*DiskUsageItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DiskUsageValue) Reset()         { *m = DiskUsageValue{} }
func (m *DiskUsageValue) String() string { return proto.CompactTextString(m) }
func (*DiskUsageValue) ProtoMessage()    {}
func (*DiskUsageValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1122009af0fe3cde, []int{8}
}

func (m *DiskUsageValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskUsageValue.Unmarshal(m, b)
}
func (m *DiskUsageValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskUsageValue.Marshal(b, m, deterministic)
}
func (m *DiskUsageValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskUsageValue.Merge(m, src)
}
func (m *DiskUsageValue) XXX_Size() int {
	return xxx_messageInfo_DiskUsageValue.Size(m)
}
func (m *DiskUsageValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskUsageValue.DiscardUnknown(m)
}

var xxx_messageInfo_DiskUsageValue proto.InternalMessageInfo

func (m *DiskUsageValue) GetItems() []*DiskUsageItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*StartMonitoringRequest)(nil), "v1grpc.StartMonitoringRequest")
	proto.RegisterType((*StatsResponse)(nil), "v1grpc.StatsResponse")
	proto.RegisterType((*CPUTimeStatValue)(nil), "v1grpc.CPUTimeStatValue")
	proto.RegisterType((*LoadStatValue)(nil), "v1grpc.LoadStatValue")
	proto.RegisterType((*NetworkStateStatValue)(nil), "v1grpc.NetworkStateStatValue")
	proto.RegisterMapType((map[string]int32)(nil), "v1grpc.NetworkStateStatValue.CountersEntry")
	proto.RegisterType((*NetworkStatItem)(nil), "v1grpc.NetworkStatItem")
	proto.RegisterType((*NetworkStatisticsValue)(nil), "v1grpc.NetworkStatisticsValue")
	proto.RegisterType((*DiskUsageItem)(nil), "v1grpc.DiskUsageItem")
	proto.RegisterType((*DiskUsageValue)(nil), "v1grpc.DiskUsageValue")
}

func init() { proto.RegisterFile("SystemStatsMonitorService.proto", fileDescriptor_1122009af0fe3cde) }

var fileDescriptor_1122009af0fe3cde = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xcd, 0x4e, 0x1b, 0x3b,
	0x14, 0xc7, 0x35, 0x09, 0x09, 0xc9, 0xe1, 0xe6, 0x92, 0x6b, 0xdd, 0x84, 0x88, 0x8a, 0x16, 0x4d,
	0x37, 0x48, 0xa8, 0x69, 0x09, 0x42, 0x42, 0x45, 0xad, 0xd4, 0x42, 0x85, 0xe8, 0x97, 0x90, 0x53,
	0x58, 0x74, 0x33, 0x32, 0x33, 0x86, 0xba, 0x49, 0xec, 0xe9, 0xd8, 0x13, 0x94, 0x65, 0x1f, 0xa4,
	0x8f, 0xd5, 0x65, 0xdf, 0xa5, 0xf2, 0xb1, 0x27, 0x24, 0x21, 0xed, 0xee, 0x7c, 0xfe, 0x7c, 0xfc,
	0xf7, 0x07, 0x3c, 0xea, 0x4f, 0xb4, 0xe1, 0xa3, 0xbe, 0x61, 0x46, 0x7f, 0x50, 0x52, 0x18, 0x95,
	0xf5, 0x79, 0x36, 0x16, 0x31, 0xef, 0xa6, 0x99, 0x32, 0x8a, 0x54, 0xc7, 0x7b, 0x37, 0x59, 0x1a,
	0x87, 0x5f, 0xa1, 0xdd, 0x37, 0x2c, 0x33, 0xbe, 0x48, 0xc8, 0x1b, 0xca, 0xbf, 0xe5, 0x5c, 0x1b,
	0xb2, 0x0b, 0xff, 0x65, 0x5c, 0xa7, 0x4a, 0x6a, 0x1e, 0x25, 0x79, 0xc6, 0x8c, 0x50, 0xb2, 0x13,
	0x6c, 0x07, 0x3b, 0x65, 0xda, 0x2c, 0x12, 0x27, 0x3e, 0x4e, 0x1e, 0x43, 0xe3, 0x96, 0x09, 0x73,
	0x57, 0x58, 0xc2, 0xc2, 0x7f, 0x6c, 0xb0, 0x28, 0x0a, 0x7f, 0x95, 0xa0, 0x81, 0x13, 0x51, 0xdf,
	0x4e, 0xf6, 0xa1, 0x16, 0xa7, 0x79, 0x24, 0xe4, 0xb5, 0x42, 0xf4, 0x5a, 0xaf, 0xd3, 0x75, 0x83,
	0x75, 0x8f, 0xcf, 0x2f, 0x3e, 0x89, 0x11, 0xb7, 0xf5, 0x97, 0x6c, 0x98, 0x73, 0xba, 0x1a, 0xa7,
	0xf9, 0x99, 0xbc, 0x56, 0xa4, 0x07, 0xf5, 0xa1, 0x62, 0x89, 0xeb, 0x2a, 0x61, 0x57, 0xab, 0xe8,
	0x7a, 0xaf, 0x58, 0x72, 0xd7, 0x52, 0xb3, 0x75, 0xd8, 0xf3, 0x0e, 0x88, 0xe4, 0xe6, 0x56, 0x65,
	0x83, 0x48, 0x1b, 0x66, 0xb8, 0x6b, 0x2e, 0x63, 0xf3, 0x56, 0xd1, 0xfc, 0xd1, 0x55, 0xd8, 0xfe,
	0x99, 0x75, 0x9b, 0x72, 0x26, 0x8c, 0xb0, 0x4b, 0xd8, 0x98, 0x85, 0x09, 0x6d, 0x44, 0xac, 0x1d,
	0x71, 0x05, 0x89, 0x0f, 0x97, 0x10, 0x5d, 0x95, 0x43, 0xb6, 0xe4, 0x62, 0x1c, 0xb9, 0x2f, 0x61,
	0x3d, 0x11, 0x7a, 0x10, 0xe5, 0x9a, 0xdd, 0xf8, 0x09, 0x2b, 0xc8, 0x6b, 0x17, 0xbc, 0x13, 0xa1,
	0x07, 0x17, 0x36, 0xeb, 0x38, 0x8d, 0xa4, 0xf0, 0x6d, 0x7f, 0x48, 0xa1, 0xb9, 0xa8, 0x1a, 0x21,
	0xb0, 0x92, 0x6b, 0x9e, 0xa1, 0xba, 0x01, 0x45, 0x9b, 0xb4, 0xa1, 0xaa, 0xf1, 0x7a, 0xa0, 0x7a,
	0x01, 0xf5, 0x9e, 0xad, 0x15, 0xc9, 0x90, 0xa3, 0x2c, 0x01, 0x45, 0x3b, 0xec, 0x43, 0x63, 0x4e,
	0x53, 0xf2, 0x3f, 0x54, 0xac, 0xaa, 0x7b, 0x9e, 0xe8, 0x9c, 0x22, 0x7a, 0xe0, 0x89, 0xce, 0xb1,
	0x0b, 0x61, 0xfa, 0xc0, 0x23, 0xbd, 0x17, 0xfe, 0x08, 0xa0, 0xb5, 0x54, 0x6c, 0x72, 0x0a, 0xb5,
	0x58, 0xe5, 0xd2, 0xf0, 0x4c, 0x77, 0x82, 0xed, 0xf2, 0xce, 0x5a, 0x6f, 0xf7, 0xaf, 0xa7, 0xd3,
	0x3d, 0xf6, 0xd5, 0x6f, 0xa4, 0xc9, 0x26, 0x74, 0xda, 0xbc, 0x79, 0x04, 0x8d, 0xb9, 0x14, 0x69,
	0x42, 0x79, 0xc0, 0x27, 0x38, 0x75, 0x9d, 0x5a, 0xd3, 0xce, 0x3c, 0xb6, 0x0c, 0x9c, 0xb9, 0x42,
	0x9d, 0xf3, 0xbc, 0x74, 0x18, 0x84, 0xdf, 0x03, 0x58, 0x9f, 0x59, 0xee, 0xcc, 0x8a, 0xd3, 0x81,
	0xd5, 0x58, 0x8d, 0x46, 0x4c, 0x26, 0x9e, 0x51, 0xb8, 0x96, 0x9c, 0x8a, 0xc4, 0x53, 0xac, 0x39,
	0x15, 0xbd, 0x8c, 0x21, 0x27, 0xfa, 0x26, 0xd4, 0xf0, 0xe5, 0xc5, 0x6a, 0x88, 0xb7, 0xa4, 0x4e,
	0xa7, 0xbe, 0xad, 0x4f, 0x55, 0x66, 0xf0, 0xb4, 0x2b, 0x14, 0xed, 0xf0, 0x14, 0xda, 0xcb, 0x6f,
	0x0f, 0x79, 0x02, 0x15, 0x61, 0xf8, 0xa8, 0x10, 0x68, 0x63, 0x89, 0x40, 0x76, 0x62, 0xea, 0xaa,
	0xc2, 0x9f, 0x01, 0x34, 0xa6, 0xf7, 0xe6, 0xcc, 0x9f, 0x73, 0xca, 0xcc, 0x17, 0xbf, 0x0f, 0xb4,
	0xed, 0x51, 0x5d, 0x6b, 0x33, 0x49, 0x9d, 0x1a, 0x75, 0xea, 0x3d, 0xbf, 0x95, 0x04, 0xb7, 0x52,
	0xc6, 0xad, 0x24, 0xf6, 0x67, 0x60, 0x63, 0x26, 0x86, 0xec, 0x6a, 0xc8, 0xa3, 0x94, 0x67, 0x31,
	0x97, 0x06, 0xf7, 0x14, 0xd0, 0xe6, 0x34, 0x71, 0xee, 0xe2, 0x64, 0x0b, 0x40, 0x48, 0x95, 0xf0,
	0x08, 0x31, 0x15, 0xc4, 0xd4, 0x31, 0x72, 0x61, 0x59, 0x87, 0xd0, 0x41, 0x47, 0x47, 0xf7, 0x91,
	0x55, 0x44, 0xb6, 0x5d, 0xfe, 0xd5, 0x02, 0x38, 0x7c, 0x01, 0xff, 0xce, 0x3f, 0x07, 0xb2, 0x3b,
	0x2f, 0x4c, 0xeb, 0xde, 0xab, 0x99, 0x91, 0xa5, 0x27, 0xe0, 0xc1, 0x1f, 0xff, 0xc8, 0xcb, 0x3d,
	0xf2, 0x16, 0xd6, 0x17, 0xfe, 0x45, 0x32, 0x7d, 0xd5, 0xcb, 0x3f, 0xcc, 0xcd, 0xd6, 0x4c, 0xfe,
	0xee, 0x8f, 0x7b, 0x16, 0xbc, 0x5e, 0xfb, 0x5c, 0xef, 0x3e, 0x3d, 0x72, 0xc9, 0xab, 0x2a, 0x9e,
	0xfa, 0xfe, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x88, 0x77, 0x25, 0x47, 0xa2, 0x05, 0x00, 0x00,
}
