// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: SystemStatsMonitorService.proto

package v1grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SystemStatsMonitorServiceV1_StartMonitoring_FullMethodName = "/v1grpc.SystemStatsMonitorServiceV1/StartMonitoring"
)

// SystemStatsMonitorServiceV1Client is the client API for SystemStatsMonitorServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemStatsMonitorServiceV1Client interface {
	StartMonitoring(ctx context.Context, in *StartMonitoringRequest, opts ...grpc.CallOption) (SystemStatsMonitorServiceV1_StartMonitoringClient, error)
}

type systemStatsMonitorServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewSystemStatsMonitorServiceV1Client(cc grpc.ClientConnInterface) SystemStatsMonitorServiceV1Client {
	return &systemStatsMonitorServiceV1Client{cc}
}

func (c *systemStatsMonitorServiceV1Client) StartMonitoring(ctx context.Context, in *StartMonitoringRequest, opts ...grpc.CallOption) (SystemStatsMonitorServiceV1_StartMonitoringClient, error) {
	stream, err := c.cc.NewStream(ctx, &SystemStatsMonitorServiceV1_ServiceDesc.Streams[0], SystemStatsMonitorServiceV1_StartMonitoring_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &systemStatsMonitorServiceV1StartMonitoringClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SystemStatsMonitorServiceV1_StartMonitoringClient interface {
	Recv() (*StatsResponse, error)
	grpc.ClientStream
}

type systemStatsMonitorServiceV1StartMonitoringClient struct {
	grpc.ClientStream
}

func (x *systemStatsMonitorServiceV1StartMonitoringClient) Recv() (*StatsResponse, error) {
	m := new(StatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SystemStatsMonitorServiceV1Server is the server API for SystemStatsMonitorServiceV1 service.
// All implementations must embed UnimplementedSystemStatsMonitorServiceV1Server
// for forward compatibility
type SystemStatsMonitorServiceV1Server interface {
	StartMonitoring(*StartMonitoringRequest, SystemStatsMonitorServiceV1_StartMonitoringServer) error
	mustEmbedUnimplementedSystemStatsMonitorServiceV1Server()
}

// UnimplementedSystemStatsMonitorServiceV1Server must be embedded to have forward compatible implementations.
type UnimplementedSystemStatsMonitorServiceV1Server struct {
}

func (UnimplementedSystemStatsMonitorServiceV1Server) StartMonitoring(*StartMonitoringRequest, SystemStatsMonitorServiceV1_StartMonitoringServer) error {
	return status.Errorf(codes.Unimplemented, "method StartMonitoring not implemented")
}
func (UnimplementedSystemStatsMonitorServiceV1Server) mustEmbedUnimplementedSystemStatsMonitorServiceV1Server() {
}

// UnsafeSystemStatsMonitorServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemStatsMonitorServiceV1Server will
// result in compilation errors.
type UnsafeSystemStatsMonitorServiceV1Server interface {
	mustEmbedUnimplementedSystemStatsMonitorServiceV1Server()
}

func RegisterSystemStatsMonitorServiceV1Server(s grpc.ServiceRegistrar, srv SystemStatsMonitorServiceV1Server) {
	s.RegisterService(&SystemStatsMonitorServiceV1_ServiceDesc, srv)
}

func _SystemStatsMonitorServiceV1_StartMonitoring_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartMonitoringRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemStatsMonitorServiceV1Server).StartMonitoring(m, &systemStatsMonitorServiceV1StartMonitoringServer{stream})
}

type SystemStatsMonitorServiceV1_StartMonitoringServer interface {
	Send(*StatsResponse) error
	grpc.ServerStream
}

type systemStatsMonitorServiceV1StartMonitoringServer struct {
	grpc.ServerStream
}

func (x *systemStatsMonitorServiceV1StartMonitoringServer) Send(m *StatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// SystemStatsMonitorServiceV1_ServiceDesc is the grpc.ServiceDesc for SystemStatsMonitorServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemStatsMonitorServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1grpc.SystemStatsMonitorServiceV1",
	HandlerType: (*SystemStatsMonitorServiceV1Server)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartMonitoring",
			Handler:       _SystemStatsMonitorServiceV1_StartMonitoring_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "SystemStatsMonitorService.proto",
}
