[logger]
level = "DEBUG"
out_paths = ["stdout"]
err_paths = ["stderr"]

[app.grpc_server]
host = "0.0.0.0"
port = "9080"

[app.stats]
cpu_enable = true
load_enable = true
scan_duration = "5s"
clean_duration = "20m"
