name: lint

on:
  push:
  # pull_request:

env:
  GO111MODULE: "on"

jobs:
  lint:
    name: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Checkout repository
        uses: actions/checkout@v3
      # - if: ${{ matrix.os == 'windows-latest' }}
      #   shell: pwsh
      #   run: |
      #     [Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Program Files\Git\usr\bin", "User")
      - name: make lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          working-directory: ${{ env.BRANCH }}
          args: --timeout 10m --verbose --path-prefix=system-stats-monitor #--skip-dirs='/opt/hostedtoolcache/go|/go/pkg/mod'