name: Go

on:
  push:

jobs:  
  build-and-test:
    name: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04,] #, windows-2019, macos-11
        include:
          - os: ubuntu-20.04
            packages: sysstat
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.20
    
    - if: ${{ matrix.packages }}
      run: sudo apt install -y ${{ matrix.packages }} && sudo netstat -lntupe
   
    - name: make build
      run: make build
    
    - name: make test
      run: make test
  coverage:
    needs: build-and-test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        parallel-finished: true